<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---------  ---------                _d1aeed</name>
   <tag></tag>
   <elementGuidId>6db63e67-1c88-4044-bd1f-89035e0dbfe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='Input2'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>province</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              --------- เลือกจังหวัด ---------
              กรุงเทพมหานคร
              กระบี่ 
              กาญจนบุรี 
              กาฬสินธุ์ 
              กำแพงเพชร 
              ขอนแก่น
              จันทบุรี
              ฉะเชิงเทรา 
              ชัยนาท 
              ชัยภูมิ 
              ชุมพร 
              ชลบุรี 
              เชียงใหม่ 
              เชียงราย 
              ตรัง 
              ตราด 
              ตาก 
              นครนายก 
              นครปฐม 
              นครพนม 
              นครราชสีมา 
              นครศรีธรรมราช 
              นครสวรรค์ 
              นราธิวาส 
              น่าน 
              นนทบุรี 
              บึงกาฬ
              บุรีรัมย์
              ประจวบคีรีขันธ์ 
              ปทุมธานี 
              ปราจีนบุรี 
              ปัตตานี 
              พะเยา 
              พระนครศรีอยุธยา 
              พังงา 
              พิจิตร 
              พิษณุโลก 
              เพชรบุรี 
              เพชรบูรณ์ 
              แพร่ 
              พัทลุง 
              ภูเก็ต 
              มหาสารคาม 
              มุกดาหาร 
              แม่ฮ่องสอน 
              ยโสธร 
              ยะลา 
              ร้อยเอ็ด 
              ระนอง 
              ระยอง 
              ราชบุรี
              ลพบุรี 
              ลำปาง 
              ลำพูน 
              เลย 
              ศรีสะเกษ
              สกลนคร
              สงขลา 
              สมุทรสาคร 
              สมุทรปราการ 
              สมุทรสงคราม 
              สระแก้ว 
              สระบุรี 
              สิงห์บุรี 
              สุโขทัย 
              สุพรรณบุรี 
              สุราษฎร์ธานี 
              สุรินทร์ 
              สตูล 
              หนองคาย 
              หนองบัวลำภู 
              อำนาจเจริญ 
              อุดรธานี 
              อุตรดิตถ์ 
              อุทัยธานี 
              อุบลราชธานี
              อ่างทอง 
              อื่นๆ
            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;form-group col-md-3&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;Input2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='Input2'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จังหวัด'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ที่อยู่ปัจจุบัน'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้อมูลการทำงาน'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ตำแหน่งงาน'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
